### ISSUE TITLE
Upgrade scripts for compatibility with HA 0.117.6

### ISSUE THREAD

**Issue by Sedins** [cederlof/home-assistant-car-heater#1]
Some of the functionality breaks with more recent Home Assistant versions, like set_visibility and others. Getting errors in the log when it tries to read configuration. Is there an updated version of the automations.yaml file?

**Comment by cederlof** [comment]
Sorry, I don't keep this repo updated and has since moved to a Node-RED
solution.

sön 15 nov. 2020 kl. 13:51 skrev Sedins <notifications@github.com>:

**Comment by Sedins** [comment]
I understand, good material to continue working on though
